export default [
  {
    title: 'Dashboard',
    to: { name: 'dashboard' },
    icon: { icon: 'tabler-layout-dashboard' },
    access: 'all',
  },
  {
    title: 'Messaging',
    to: { name: 'messaging' },
    icon: { icon: 'tabler-message' },
    access: 'all',
  },
  { heading: 'Operations', access: 'company' },
  {
    title: 'Raw Materials',
    to: { name: 'materials-tab', params: { tab: 'dashboard' } },
    icon: { icon: 'tabler-brand-unity' },
    access: 'company',
  },
  {
    title: 'Production Unit',
    to: { name: 'production-tab', params: { tab: 'dashboard' } },
    icon: { icon: 'tabler-building-factory' },
    access: 'company',
    badgeContent: '2',
    badgeClass: 'bg-error',
  },
  {
    title: 'Finished Goods',
    to: { name: 'finished-goods-tab', params: { tab: 'products' } },
    icon: { icon: 'tabler-building-warehouse' },
    access: 'company',
  },
  {
    title: 'Quality Control',
    to: { name: 'quality-control-tab', params: { tab: 'stock' } },
    icon: { icon: 'tabler-discount-check' },
    access: 'company',
  },
  { heading: 'Analytics', access: 'company' },
  {
    title: 'Traceability',
    to: { name: 'traceability' },
    icon: { icon: 'tabler-track-prev' },
    access: 'company',
  },
  {
    title: 'Reports',
    to: { name: 'reports' },
    icon: { icon: 'tabler-chart-infographic' },
    access: 'company',
  },
  { heading: 'Finance', access: 'company' },
  {
    title: 'Sales',
    to: { name: 'sales' },
    icon: { icon: 'tabler-cash' },
    access: 'company',
  },
  {
    title: 'Accounting',
    to: { name: 'accounting' },
    icon: { icon: 'tabler-brand-google-analytics' },
    access: 'company',
  },
  { heading: 'Organization', access: 'company' },
  {
    title: 'System Settings',
    to: { name: 'system-settings-tab', params: { tab: "company" } },
    icon: { icon: 'tabler-settings' },
    access: 'company',
  },
  {
    title: 'Help & Support',
    to: { name: 'help-and-support' },
    icon: { icon: 'tabler-help' },
    access: 'company',
  },
  { heading: 'Client', access: 'velma' },
  {
    title: 'Companies',
    to: { name: 'companies-tab' },
    icon: { icon: 'tabler-settings' },
    access: 'velma',
  },
  {
    title: 'Help & Support',
    to: { name: 'admin-support' },
    icon: { icon: 'tabler-help' },
    access: 'velma',
  },
  { heading: 'Finance', access: 'velma' },
  {
    title: 'Accounting',
    to: { name: 'accounting' },
    icon: { icon: 'tabler-help' },
    access: 'velma',
  },
  { heading: 'Internal', access: 'velma' },
  {
    title: 'Systems Settings',
    to: { name: 'admin-systems-settings-tab' },
    icon: { icon: 'tabler-help' },
    access: 'velma',
  },
]
      